export const sampleProducts = [
    { name: 'Laptop Pro', brand: 'TechCorp', category: 'Electronics', stockQuantity: 50, shopQuantity: 10, price: 1200.00, imageUrl: 'https://picsum.photos/seed/laptoppro/600/400' },
    { name: 'Smartphone X', brand: 'ConnectMe', category: 'Electronics', stockQuantity: 150, shopQuantity: 25, price: 799.99, imageUrl: 'https://picsum.photos/seed/phonex/600/400' },
    { name: 'Wireless Headphones', brand: 'SoundWave', category: 'Audio', stockQuantity: 200, shopQuantity: 50, price: 149.99, imageUrl: 'https://picsum.photos/seed/headphones/600/400' },
    { name: 'Smart Watch 2', brand: 'FitLife', category: 'Wearables', stockQuantity: 80, shopQuantity: 20, price: 249.95, imageUrl: 'https://picsum.photos/seed/smartwatch/600/400' },
    { name: '4K TV 55-inch', brand: 'Vision', category: 'Home Entertainment', stockQuantity: 30, shopQuantity: 5, price: 499.00, imageUrl: 'https://picsum.photos/seed/tv/600/400' },
    { name: 'Gaming Console', brand: 'GameOn', category: 'Gaming', stockQuantity: 60, shopQuantity: 15, price: 399.99, imageUrl: 'https://picsum.photos/seed/console/600/400' },
    { name: 'Organic Cotton T-Shirt', brand: 'EcoThreads', category: 'Apparel', stockQuantity: 300, shopQuantity: 75, price: 25.00, imageUrl: 'https://picsum.photos/seed/tshirt/600/400' },
    { name: 'Classic Blue Jeans', brand: 'DenimCo', category: 'Apparel', stockQuantity: 250, shopQuantity: 50, price: 75.50, imageUrl: 'https://picsum.photos/seed/jeans/600/400' },
    { name: 'Running Shoes', brand: 'QuickStep', category: 'Footwear', stockQuantity: 120, shopQuantity: 30, price: 110.00, imageUrl: 'https://picsum.photos/seed/shoes/600/400' },
    { name: 'Leather Backpack', brand: 'UrbanCarry', category: 'Accessories', stockQuantity: 90, shopQuantity: 20, price: 89.99, imageUrl: 'https://picsum.photos/seed/backpack/600/400' },
    { name: 'Gourmet Coffee Beans', brand: 'MorningBrew', category: 'Groceries', stockQuantity: 500, shopQuantity: 100, price: 18.50, imageUrl: 'https://picsum.photos/seed/coffee/600/400' },
    { name: 'Extra Virgin Olive Oil', brand: 'HealthyFats', category: 'Groceries', stockQuantity: 180, shopQuantity: 40, price: 22.00, imageUrl: 'https://picsum.photos/seed/oliveoil/600/400' },
    { name: 'The Silent Forest', brand: 'PageTurners', category: 'Books', stockQuantity: 75, shopQuantity: 25, price: 14.99, imageUrl: 'https://picsum.photos/seed/book/600/400' },
    { name: 'Cosmic Adventure', brand: 'Imagination', category: 'Toys', stockQuantity: 130, shopQuantity: 30, price: 29.95, imageUrl: 'https://picsum.photos/seed/toy/600/400' },
    {
      name: 'Herbal Shampoo',
      brand: 'NatureEssence',
      category: 'Personal Care',
      stockQuantity: 220,
      shopQuantity: 50,
      price: 12.00,
      imageUrl: 'https://picsum.photos/seed/shampoo/600/400'
    },
    { name: 'Stainless Steel Pan', brand: 'HomeChef', category: 'Cookware', stockQuantity: 100, shopQuantity: 20, price: 45.00, imageUrl: 'https://picsum.photos/seed/pan/600/400' },
    { name: 'Yoga Mat', brand: 'ZenFlow', category: 'Sports', stockQuantity: 160, shopQuantity: 40, price: 35.00, imageUrl: 'https://picsum.photos/seed/yogamat/600/400' },
    { name: 'Desk Lamp', brand: 'BrightIdeas', category: 'Office Supplies', stockQuantity: 110, shopQuantity: 30, price: 49.99, imageUrl: 'https://picsum.photos/seed/lamp/600/400' },
    { name: 'Robot Vacuum', brand: 'CleanBot', category: 'Home Appliances', stockQuantity: 45, shopQuantity: 10, price: 299.00, imageUrl: 'https://picsum.photos/seed/vacuum/600/400' },
    { name: 'Wall Art Print', brand: 'DecorVibes', category: 'Home Decor', stockQuantity: 95, shopQuantity: 25, price: 55.00, imageUrl: 'https://picsum.photos/seed/wallart/600/400' },
  ];
  
